# Generated by Django 2.1.5 on 2019-01-24 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_person_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='salary',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
    ]
